import {API_KEY, AUTHDOMAIN, PROJECTID, STORAGEBUCKET, MESSAGINGSENDERID, APPID, MEASUREMENTID} from '@env'

export default{
    API_KEY,
    AUTHDOMAIN, 
    PROJECTID, 
    STORAGEBUCKET, 
    MESSAGINGSENDERID, 
    APPID, 
    MEASUREMENTID
}
