version: "3.8"

services: 
  # Postgres Instance
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pinkthursday
    ports:
      - "5433:5432"
  
  # Apollo Server
  server:
    build: .
    container_name: server
    image: pinkthursday-apollo-server
    restart: always
    depends_on: 
      - postgres
    ports:
      - "4000:4000"