version: "3.8"

services: 
  # Postgres Instance
  postgres:
    container_name: postgres
    image: postgres:alpine
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pinkthursday
    ports:
      - "5432:5432"
  
  # Redis
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  # Apollo Server
  server:
    build: .
    container_name: server
    image: pinkthursday-apollo-server
    restart: always
    volumes:
      - .:/usr/src
    links:
      - postgres
      - redis
    depends_on: 
      - postgres
      - redis
    ports:
      - "${PORT}:${PORT}"
      - "9229:9229"